In [113]:
import pandas as pd
import numpy as np
from sklearn import datasets


In [114]:
wine = datasets.load_wine()
wine

{'DESCR': 'Wine Data Database\n====================\n\nNotes\n-----\nData Set Characteristics:\n    :Number of Instances: 178 (50 in each of three classes)\n    :Number of Attributes: 13 numeric, predictive attributes and the class\n    :Attribute Information:\n \t\t- 1) Alcohol\n \t\t- 2) Malic acid\n \t\t- 3) Ash\n\t\t- 4) Alcalinity of ash  \n \t\t- 5) Magnesium\n\t\t- 6) Total phenols\n \t\t- 7) Flavanoids\n \t\t- 8) Nonflavanoid phenols\n \t\t- 9) Proanthocyanins\n\t\t- 10)Color intensity\n \t\t- 11)Hue\n \t\t- 12)OD280/OD315 of diluted wines\n \t\t- 13)Proline\n        \t- class:\n                - class_0\n                - class_1\n                - class_2\n\t\t\n    :Summary Statistics:\n    \n    ============================= ==== ===== ======= =====\n                                   Min   Max   Mean     SD\n    ============================= ==== ===== ======= =====\n    Alcohol:                      11.0  14.8    13.0   0.8\n    Malic Acid:                   0.74  5.80   

In [115]:
wine.data

array([[  1.42300000e+01,   1.71000000e+00,   2.43000000e+00, ...,
          1.04000000e+00,   3.92000000e+00,   1.06500000e+03],
       [  1.32000000e+01,   1.78000000e+00,   2.14000000e+00, ...,
          1.05000000e+00,   3.40000000e+00,   1.05000000e+03],
       [  1.31600000e+01,   2.36000000e+00,   2.67000000e+00, ...,
          1.03000000e+00,   3.17000000e+00,   1.18500000e+03],
       ..., 
       [  1.32700000e+01,   4.28000000e+00,   2.26000000e+00, ...,
          5.90000000e-01,   1.56000000e+00,   8.35000000e+02],
       [  1.31700000e+01,   2.59000000e+00,   2.37000000e+00, ...,
          6.00000000e-01,   1.62000000e+00,   8.40000000e+02],
       [  1.41300000e+01,   4.10000000e+00,   2.74000000e+00, ...,
          6.10000000e-01,   1.60000000e+00,   5.60000000e+02]])

In [116]:
wine.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [117]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [164]:
X_train,X_test,y_train,y_test = train_test_split(wine['data'],wine['target'],test_size=0.2)

In [165]:
logR =LogisticRegression(multi_class='ovr')
logR.fit(X_train,y_train)
confidence = logR.score(X_test,y_test)
print(confidence)

0.888888888889


In [166]:
prediction = logR.predict(X_test)
print(prediction)

[0 0 2 1 1 1 0 1 0 1 1 0 1 2 2 0 1 2 0 1 0 1 0 1 0 2 1 2 2 2 1 1 0 1 0 2]


In [167]:
from sklearn.svm import SVC #support vector classifier
model = SVC(kernel ='rbf',C=1E120) #E-exponential 2.71^10
model.fit(X_train,y_train)
confidence1 = model.score(X_test,y_test)
print(confidence1)

0.666666666667


In [126]:
X_train

array([[  1.34800000e+01,   1.67000000e+00,   2.64000000e+00, ...,
          5.70000000e-01,   1.78000000e+00,   6.20000000e+02],
       [  1.25800000e+01,   1.29000000e+00,   2.10000000e+00, ...,
          5.80000000e-01,   1.55000000e+00,   6.40000000e+02],
       [  1.38700000e+01,   1.90000000e+00,   2.80000000e+00, ...,
          1.25000000e+00,   3.40000000e+00,   9.15000000e+02],
       ..., 
       [  1.28200000e+01,   3.37000000e+00,   2.30000000e+00, ...,
          7.20000000e-01,   1.75000000e+00,   6.85000000e+02],
       [  1.31600000e+01,   2.36000000e+00,   2.67000000e+00, ...,
          1.03000000e+00,   3.17000000e+00,   1.18500000e+03],
       [  1.42200000e+01,   1.70000000e+00,   2.30000000e+00, ...,
          9.40000000e-01,   3.31000000e+00,   9.70000000e+02]])

In [ ]:
# Find confusion matrix and heatmap