# Numpy 
- Numpy internally stores data in continuous block of memory.
- Written in C-language
- Faster than list and use less memory.

In [3]:
import numpy as np

arr = np.arange(1000000)
arr
listarr = list(range(1000000))
listarr
%time for _ in range(10):arr2 = arr*2


Wall time: 31.3 ms


In [17]:
%time for _ in range(10):listarr = [x * 2 for x in listarr]

Wall time: 1.46 s


In [73]:
np.arange(6).reshape(2,3)
# 0 to n-1

array([[0, 1, 2],
       [3, 4, 5]])

In [28]:
data = np.random.randn(3,4)
data


array([[-0.71244485, -0.55475829, -1.06899507, -0.44612727],
       [-0.05852393, -1.20660705,  0.9035627 ,  0.20842024],
       [ 0.31692541, -1.57801525, -0.85180523, -0.6285183 ]])

In [33]:
data * 10

array([[ -7.12444852,  -5.54758287, -10.68995066,  -4.46127266],
       [ -0.58523934, -12.06607046,   9.03562697,   2.08420242],
       [  3.16925413, -15.78015246,  -8.51805225,  -6.28518301]])

In [38]:
data + data

array([[-1.4248897 , -1.10951657, -2.13799013, -0.89225453],
       [-0.11704787, -2.41321409,  1.80712539,  0.41684048],
       [ 0.63385083, -3.15603049, -1.70361045, -1.2570366 ]])

In [40]:
data.dtype

dtype('float64')

In [42]:
data.shape

(3, 4)

In [44]:
#  Creating Ndarray using array function
a = [6,8,4,9,6]
arr1 = np.array(a)
arr1

array([6, 8, 4, 9, 6])

In [47]:
b = [[7,2,6,4,8],[40,56,48,45,75]]
arr2 = np.array(b)
arr2

array([[ 7,  2,  6,  4,  8],
       [40, 56, 48, 45, 75]])

In [49]:
c = np.array([[80,45,10,13],[78,45,12,36],[85,45,96,35]])
c

array([[80, 45, 10, 13],
       [78, 45, 12, 36],
       [85, 45, 96, 35]])

In [66]:
c[1:,2:]

array([[12, 36],
       [96, 35]])

In [67]:
c.ndim

2

In [70]:
np.array(111)

array(111)

In [71]:
c.size

12

In [81]:
d = np.array([[80.50,45,10,13],[78,45,12,36],[85,45,96,35],[45,25,16,25]])
d

array([[ 80.5,  45. ,  10. ,  13. ],
       [ 78. ,  45. ,  12. ,  36. ],
       [ 85. ,  45. ,  96. ,  35. ],
       [ 45. ,  25. ,  16. ,  25. ]])

In [82]:
d.nbytes

128

In [83]:
np.zeros(10).reshape(2,5)

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [84]:
np.ones(10).reshape(2,5)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [94]:
np.empty((2,3,2))


array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]])

In [101]:
np.ones_like(2)

array(1)

In [107]:
np.full_like(2,2)

array(2)

In [6]:
b = [12,2,5,1,4],[78,96,25,10,23],[3,6,5,4,82]
b

([12, 2, 5, 1, 4], [78, 96, 25, 10, 23], [3, 6, 5, 4, 82])

In [14]:
int_arr = np.array(b,dtype=np.int64)
int_arr

array([[12,  2,  5,  1,  4],
       [78, 96, 25, 10, 23],
       [ 3,  6,  5,  4, 82]], dtype=int64)

In [15]:
float_arr = int_arr.astype(np.float64)

In [16]:
float_arr

array([[ 12.,   2.,   5.,   1.,   4.],
       [ 78.,  96.,  25.,  10.,  23.],
       [  3.,   6.,   5.,   4.,  82.]])

In [20]:
a,b=6,7
a,b = b,a
print(a,b)

7 6


In [25]:
a = np.array([[5,2,3,4]])
a

array([[5, 2, 3, 4]])

In [26]:
a ** 2

array([[25,  4,  9, 16]], dtype=int32)