# NUMPY BASICS

In [2]:
import numpy as np

In [7]:
np_array=np.array([2,3,4,5,6,7,8,9])
np_array
print(np_array)

[2 3 4 5 6 7 8 9]


In [8]:
type(np_array)

numpy.ndarray

# Difference between list and NDArray

In [11]:
list1=['pizza','pizaaaa','topiing pizza','Dominos pizza']
print((list1)*2)

['pizza', 'pizaaaa', 'topiing pizza', 'Dominos pizza', 'pizza', 'pizaaaa', 'topiing pizza', 'Dominos pizza']


In [21]:
py_list=[1,2,3,4,5,6,7,8]
print((py_list)*2)

[1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8]


In [22]:
numpy_array=np.array([1,2,3,4,5,6,7,8])

In [23]:
print(numpy_array * 2)

[ 2  4  6  8 10 12 14 16]


In [24]:
py_list2=py_list + py_list
print(py_list2)

[1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8]


In [25]:
numpy_array2=numpy_array + numpy_array + numpy_array

In [26]:
print (numpy_array2)

[ 3  6  9 12 15 18 21 24]


# SOME NUMPY ATTRIBUTES

In [32]:
#numpy_array = np.array([(2,3,4,5),(4,5,6,7)])
numpy_array = np.array([[2,3,4,5],[4,5,6,7]],dtype=float)

print (numpy_array)

[[ 2.  3.  4.  5.]
 [ 4.  5.  6.  7.]]


In [30]:
type(numpy_array)

numpy.ndarray

# other METHODs TO GENERATE ARRAY

In [35]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [36]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.linspace(1,10,3,dtype=float)

array([  1. ,   5.5,  10. ])

In [39]:
np.linspace(1,10,dtype=float)

array([  1.        ,   1.18367347,   1.36734694,   1.55102041,
         1.73469388,   1.91836735,   2.10204082,   2.28571429,
         2.46938776,   2.65306122,   2.83673469,   3.02040816,
         3.20408163,   3.3877551 ,   3.57142857,   3.75510204,
         3.93877551,   4.12244898,   4.30612245,   4.48979592,
         4.67346939,   4.85714286,   5.04081633,   5.2244898 ,
         5.40816327,   5.59183673,   5.7755102 ,   5.95918367,
         6.14285714,   6.32653061,   6.51020408,   6.69387755,
         6.87755102,   7.06122449,   7.24489796,   7.42857143,
         7.6122449 ,   7.79591837,   7.97959184,   8.16326531,
         8.34693878,   8.53061224,   8.71428571,   8.89795918,
         9.08163265,   9.26530612,   9.44897959,   9.63265306,
         9.81632653,  10.        ])

In [41]:
np.linspace(1,10,num=7,endpoint=False,dtype=float)
#endpoint=false  doesnt touch the end point i.e 10 if it is true it goes upto 10

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571])

In [47]:
np.arange(1,9, ).reshape(3,3)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [44]:
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [45]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [46]:
#identical matrix

np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [49]:
np.random.random(3)

array([ 0.53153365,  0.6681144 ,  0.53981344])

In [51]:
array_num=np.random.random((3,5))
array_num

array([[ 0.58986453,  0.60806717,  0.39226974,  0.36334801,  0.89987839],
       [ 0.23913996,  0.82723613,  0.40027075,  0.92031624,  0.61922753],
       [ 0.92519333,  0.51706663,  0.7593418 ,  0.48108375,  0.39781491]])

In [65]:
#slicing
#array_num[row,col]
array_num[1:4,0:4]

array([[ 0.23913996,  0.82723613,  0.40027075,  0.92031624],
       [ 0.92519333,  0.51706663,  0.7593418 ,  0.48108375]])

# broadcasting

#The term broadcasting describes how numpy treats with different shapes during arithmetic oparations-Scipy.org

In [72]:
np_val=np.arange(1,10)
np_val

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
np_val.shape

(9,)

In [74]:
np_val1=np.ones(7)
np_val1

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [75]:
np_val1.shape

(7,)

In [76]:
np_val + np_val1

ValueError: operands could not be broadcast together with shapes (9,) (7,) 

In [78]:
new_np_val=np_val.reshape(9,1)
new_np_val

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [79]:
new_np_val + np_val1

array([[  2.,   2.,   2.,   2.,   2.,   2.,   2.],
       [  3.,   3.,   3.,   3.,   3.,   3.,   3.],
       [  4.,   4.,   4.,   4.,   4.,   4.,   4.],
       [  5.,   5.,   5.,   5.,   5.,   5.,   5.],
       [  6.,   6.,   6.,   6.,   6.,   6.,   6.],
       [  7.,   7.,   7.,   7.,   7.,   7.,   7.],
       [  8.,   8.,   8.,   8.,   8.,   8.,   8.],
       [  9.,   9.,   9.,   9.,   9.,   9.,   9.],
       [ 10.,  10.,  10.,  10.,  10.,  10.,  10.]])

In [80]:
new_np_val * np_val1

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [84]:
np.ceil(2.5)

3.0